# Generated by Django 4.2.23 on 2025-07-06 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_video_tags_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
