# Generated by Django 4.2.23 on 2025-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
